CASINO_FIRST_LETTERS = ["c", "C", "с", "С"]
ESCORT_FIRST_LETTERS = ["e", "E", "е", "Е"]
TRADING_FIRST_LETTERS = ["t", "T", "т", "Т"]

SERVICE_FIRST_LETTERS = [
    *CASINO_FIRST_LETTERS,
    *ESCORT_FIRST_LETTERS,
    *TRADING_FIRST_LETTERS,
]
